### ISSUE TITLE
Document meaning of `<`, `+` and `>` on offsets

### ISSUE THREAD

**Issue by cirosantilli** [getreu/stringsext#13]
E.g. on the example given on README:

```
stringsext -tx -e utf-8 -e utf-16le -e utf-16be \
           -n 10 -a None -u African  /dev/disk/by-uuid/567a8410
```

outputting:

```
 3de2fff0+	(b UTF-16LE)	ݒݓݔݕݖݗݙݪ
 3de30000+	(b UTF-16LE)	ݫݱݶݷݸݹݺ
<3de36528 	(a UTF-8)	فيأنمامعكلأورديافىهولملكاولهبسالإنهيأيقدهلثمبهلوليبلايبكشيام
>3de36528+	(a UTF-8)	أمنتبيلنحبهممشوش
<3de3a708 	(a UTF-8)	علىإلىهذاآخرعددالىهذهصورغيركانولابينعرضذلكهنايومقالعليانالكن
>3de3a708+	(a UTF-8)	حتىقبلوحةاخرفقطعبدركنإذاكمااحدإلافيهبعضكيفبح
 3de3a780+	(a UTF-8)	ثومنوهوأناجدالهاسلمعندليسعبرصلىمنذبهاأنهمثلكنتالاحيثمصرشرححو
 3de3a7f8+	(a UTF-8)	لوفياذالكلمرةانتالفأبوخاصأنتانهاليعضووقدابنخيربنتلكمشاءوهياب
 3de3a870+	(a UTF-8)	وقصصومارقمأحدنحنعدمرأياحةكتبدونيجبمنهتحتجهةسنةيتمكرةغزةنفسبي
 3de3a8e8+	(a UTF-8)	تللهلناتلكقلبلماعنهأولشيءنورأمافيكبكلذاترتببأنهمسانكبيعفقدحس
 3de3a960+	(a UTF-8)	نلهمشعرأهلشهرقطرطلب
 3df4cca8 	(c UTF-16BE)	փօև։֋֍֏׹
<3df4cd20 	(c UTF-16BE)	־ֿ׀ׁׂ׃ׅׄ׆ׇ׈׉׊׋
```

what is the meaning of `<`, `+` and `>` characters. Perhaps it is even harder to understand for non speaker of the sample languages like me.

It seems:

- `+` is linked to the enforce line limit of `-q`
- `>` seems to mean raw newline without `+`

**Comment by getreu** [comment]
`<>`: The decoding library used in `stringsext` can not determine the exact location of the finding. See explanation in the [Stringsext Documentation](https://blog.getreu.net/projects/stringsext/stringsext--manpage.html#output-format)

`+`: The string completes the previous

**Comment by cirosantilli** [comment]
Oops missed that section, thanks.

**Comment by cirosantilli** [comment]
I wonder why the algorithm doesn't always find the exact position, that's a bit annoying.

**Comment by getreu** [comment]
[Limitations related to the encoding_rs library](https://blog.getreu.net/projects/stringsext/stringsext--manpage.html#limitations-related-to-the-encoding_rs-library)
