### ISSUE TITLE
Implement support for Regex filtering of strings.

### ISSUE THREAD

**Issue by KelSolaar** [getreu/stringsext#3]
Hi,

Follow-up of the email thread: I was looking at using _stringsext_ to scrape paths in binary files, however, piping the output to _grep_ for example, is very slow for large files, e.g. 25Go, I was thinking that having native Regex filtering of the found strings would maybe help here instead of piping a torrent of data via stdout.

Cheers,

Thomas

**Comment by getreu** [comment]
> having native Regex filtering of the found strings

There is a trade-off between speed and flexibility. As I understood, your main use-case is to scan quickly for path strings in binary data. The new Stringsext version 2 has some support for this, try:

```
stringsext --grep-char=47 input.raw 
```
