### ISSUE TITLE
Suggestion: line numbers

### ISSUE THREAD

**Issue by STashakkori** [getreu/stringsext#8]
Hello. Figured I would give some feedback. This would be even better if it was possible to print the line numbers of the occurrences. Thanks

**Comment by getreu** [comment]
Thank you for your feedback. By design `stringsext` is a binary stream filter. In such streams you identify your position by a byte offset. If you want to operate line by line, other tools like `grep` are better suited.
`stringsext` follows the UXNIX paradigm: “do one thing only, but do it well”!

**Comment by STashakkori** [comment]
I will have to kindly disagree. This tool is designed to show utf-8 strings in a file. However, knowing where in the file that string resides is an important detail that most real use will require. Hence, why the strings command provides that information. I know adding such a feature is going to be difficult so I understand the hesitation. So perhaps instead might I suggest printing the byte offset at which each token is found in the output. That way someone can still locate the string if they use the right editor. Thanks

**Comment by getreu** [comment]
> So perhaps instead might I suggest printing the byte offset at which each token is found in the output. That way someone can still locate the string if they use the right editor.

Have you tried:

    stringsext -t d <input file>

Alternatively you can print the offset with `-t x` in hexadecimal notation, or `-t o` in octal.

**Comment by STashakkori** [comment]
Incredible. Absolutely outstanding. Thank you
