### ISSUE TITLE
Byte offsets not accurate

### ISSUE THREAD

**Issue by STashakkori** [getreu/stringsext#9]
Hello and thank you. The byte offsets produced by using the -t flag don't appear to be entirely accurate. There are duplicates. Reading the manual it appears that they signify either a range (<), (>) or indicate that the line is an extension of a line passed the length limit (+). Somewhat of an approximation rather than an exact location like it is with the standard strings command. Is this because of the nature of the worker threads not being aware of one another and able to piece together an exact picture?

**Comment by getreu** [comment]
> Reading the manual it appears that they signify either a range (<), (>) or indicate that the line is an extension of a line passed the length limit (+). Somewhat of an approximation rather than an exact location like it is with the standard strings command.

Yes.
 
> Is this because of the nature of the worker threads not being aware of one another and able to piece together an exact picture?

The reason is a design choice: [batch processing](https://blog.getreu.net/projects/forensic-tool-development-with-rust/#req-batch-processing).

**Comment by getreu** [comment]
To detail this a little: the reason for batch processing is, that `stringsext` is designed to also work on (embedded) systems with very little RAM. From this ensue some limitations. For example: sometimes it it not possible to decide in the current batch whether a string sequence should be printed or not. These postponed strings might be printed in the following batch. In order not to not disturb the overall ordering these strings will be marked '<', e.g. '<57b'.

Another set of limitations are origin of [Limitations related to the encoding_rs library](https://blog.getreu.net/projects/stringsext/stringsext--manpage.html#limitations-related-to-the-encoding_rs-library).
